### ISSUE TITLE
m2e JAX-B: Maven Execution using Eclipse's default JDK, instead of project's JDK

### ISSUE THREAD

**Issue by teh-hippo** [bitstrings/m2e-connectors-p2#1]
Hi,

My Eclipse runs on 1.7 and has 1.7 as the default for projects.

This has previously been working fine.  If I set the compiler plugin's source & target variables to 1.6, as long as I have a 1.6 installation included in my list of 'Installed JDKs', m2e will update the compiler settings for that project and all will be well..

I've had an issue with the JAX-B plugin where it wasn't generating classes as expected.  We eventually traced it down to whether it was being compiled through JDK 1.6 or 1.7.  Seems that the plugin will just use Eclipse's default compiler, instead of what the project is set to.

Is this able to be fixed?

:)

Michael

**Comment by bitstrings** [comment]
Hello,

are you using the codehaus mojo JAXB-2 Maven Plugin?

or

the java.net Maven 2 JAXB 2.x Plugin?

Also, the codehaus plugin now uses it's own m2e lifecycle mapping so my connector is not used.

I highly doubt this is a connector issue since the connector is only a proxy to the actual processing.

I do have a similar environment so I might be able to reproduce your problem.

**Comment by teh-hippo** [comment]
(Sorry for the delay)

Codehaus is the plugin, but I'm using this connector... at least I thought I was?  I'm using an older version (restriction on the product) at the moment, so maybe I'm not benefitting from their in-built mapping?

M
